[package]
name = "dexterity-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared utilities for Dexterity decompiler"

[dependencies]
lazy_static = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
