[package]
name = "jadx-deobf"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Deobfuscation support for jadx-rust"

[dependencies]
jadx-ir.workspace = true
regex.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
